### ISSUE TITLE
Remaning topics

### ISSUE THREAD

**Issue by mingrammer** [mingrammer/gobyexample#1]
- [x] 채널 닫기
- [x] 채널에서의 Range
- [x] 타이머
- [x] 티커
- [x] 워커 풀
- [x] 속도 제한
- [x] 원자성 카운터
- [x] 뮤텍스
- [x] 상태있는 고루틴
- [x] 정렬
- [x] 함수를 사용한 정렬
- [x] 패닉
- [x] 지연
- [x] 컬렉션 함수
- [x] 문자열 함수
- [x] 문자열 포맷팅
- [x] 정규표현식
- [x] JSON
- [x] 시간
- [x] 타임스탬프
- [x] 시간 포맷팅/파싱
- [x] 난수
- [x] 숫자 파싱
- [x] URL 파싱
- [x] SHA1 해시
- [x] Base64 인코딩
- [x] 파일 읽기
- [x] 파일 쓰기
- [x] 라인 필터
- [x] 커맨드라인 인자
- [x] 커맨드라인 플래그
- [x] 환경변수
- [x] 프로세스 생성
- [x] 프로세스 실행
- [x] 시그널
- [x] 종료

**Comment by Suckzoo** [comment]
@mingrammer 환경변수 작업 시작합니다.

**Comment by mingrammer** [comment]
@Suckzoo 넵! 내일 완성할 예정인데 내일까지 주시면 감사하겠습니다!

**Comment by Suckzoo** [comment]
@mingrammer 늦어도 내일 밤까지는 드리겠습니다.
프로세스 생성 / 프로세스 실행 / 시그널 / 종료 까지 맡겠습니다.
